language: python
python:
    - "2.7"
    - "3.2"
before_install:
    - sudo apt-get install libatlas3gf-base libatlas-dev liblapack-dev
install:
    - pip install scipy
    - python setup.py install
script: python tests/tests.py
