language: python
python:
    - "2.7"
    - "3.2"
virtualenv:
    system_site_packages: true
addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - python3-numpy
            - python3-scipy
script: nosetests krypy/tests
