sudo: false
language: python
python:
    - "2.7"
    - "3.6"
addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - python3-numpy
            - python3-scipy
script: nosetests krypy/tests
